FROM python:3.9-slim

WORKDIR /app

COPY time_client.py .
COPY requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt

# Desativar o buffering do Python
ENV PYTHONUNBUFFERED=1

# O ID do cliente será passado como argumento
CMD ["python", "time_client.py"] 