FROM python:3.9-slim

WORKDIR /app

COPY time_server.py .
COPY requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt

# Desativar o buffering do Python
ENV PYTHONUNBUFFERED=1

EXPOSE 8000

CMD ["python", "time_server.py"] 